openapi: 3.0.1
info:
  title: Swagger Petstore
  description: "This spec is mainly for testing Petstore server and contains fake\
    \ endpoints, models. Please do not use this for any other purpose. Special characters:\
    \ \" \\"
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://petstore.swagger.io:80/v2
tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /pet:
    put:
      tags:
      - pet
      summary: Update an existing pet
      operationId: update_pet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}
        "405":
          description: Validation exception
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
    post:
      tags:
      - pet
      summary: Add a new pet to the store
      operationId: add_pet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        "405":
          description: Invalid input
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /pet/findByStatus:
    get:
      tags:
      - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: find_pets_by_status
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            default: available
            enum:
            - available
            - pending
            - sold
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
                x-content-type: application/xml
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        "400":
          description: Invalid status value
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /pet/findByTags:
    get:
      tags:
      - pet
      summary: Finds Pets by tags
      description: "Multiple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing."
      operationId: find_pets_by_tags
      parameters:
      - name: tags
        in: query
        description: Tags to filter by
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
                x-content-type: application/xml
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        "400":
          description: Invalid tag value
          content: {}
      deprecated: true
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /pet/{petId}:
    get:
      tags:
      - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: get_pet_by_id
      parameters:
      - name: petId
        in: path
        description: ID of pet to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.pet_controller
    post:
      tags:
      - pet
      summary: Updates a pet in the store with form data
      operationId: update_pet_with_form
      parameters:
      - name: petId
        in: path
        description: ID of pet that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/pet_petId_body'
      responses:
        "405":
          description: Invalid input
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
    delete:
      tags:
      - pet
      summary: Deletes a pet
      operationId: delete_pet
      parameters:
      - name: api_key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: petId
        in: path
        description: Pet id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid pet value
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /pet/{petId}/uploadImage:
    post:
      tags:
      - pet
      summary: uploads an image
      operationId: upload_file
      parameters:
      - name: petId
        in: path
        description: ID of pet to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/petId_uploadImage_body'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /randomPet:
    get:
      tags:
      - pet
      operationId: get_random_pet
      responses:
        "200":
          description: a single random pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SinglePetResponse'
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /allPets:
    get:
      tags:
      - pet
      operationId: get_all_pets
      responses:
        "200":
          description: a single random pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllPetsResponse'
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /pet/category:
    post:
      tags:
      - pet
      operationId: do_category_stuff
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubCategory'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-openapi-router-controller: swagger_server.controllers.pet_controller
  /store/inventory:
    get:
      tags:
      - store
      summary: Returns pet inventories by status
      description: Returns a map of status codes to quantities
      operationId: get_inventory
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
                x-content-type: application/json
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.store_controller
  /store/order:
    post:
      tags:
      - store
      summary: Place an order for a pet
      operationId: place_order
      requestBody:
        description: order placed for purchasing the pet
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        "400":
          description: Invalid Order
          content: {}
      x-openapi-router-controller: swagger_server.controllers.store_controller
  /store/order/{order_id}:
    get:
      tags:
      - store
      summary: Find purchase order by ID
      description: For valid response try integer IDs with value <= 5 or > 10. Other
        values will generated exceptions
      operationId: get_order_by_id
      parameters:
      - name: order_id
        in: path
        description: ID of pet that needs to be fetched
        required: true
        style: simple
        explode: false
        schema:
          maximum: 5
          minimum: 1
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Order not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.store_controller
    delete:
      tags:
      - store
      summary: Delete purchase order by ID
      description: For valid response try integer IDs with value < 1000. Anything
        above 1000 or nonintegers will generate API errors
      operationId: delete_order
      parameters:
      - name: order_id
        in: path
        description: ID of the order that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Order not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.store_controller
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: create_user
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /user/createWithArray:
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      operationId: create_users_with_array_input
      requestBody:
        description: List of user object
        content:
          '*/*':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /user/createWithList:
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      operationId: create_users_with_list_input
      requestBody:
        description: List of user object
        content:
          '*/*':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      operationId: login_user
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when toekn expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
                x-content-type: application/xml
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logout_user
      responses:
        default:
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /user/{username}:
    get:
      tags:
      - user
      summary: Get user by user name
      operationId: get_user_by_name
      parameters:
      - name: username
        in: path
        description: 'The name that needs to be fetched. Use user1 for testing. '
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
    put:
      tags:
      - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: update_user
      parameters:
      - name: username
        in: path
        description: name that need to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Updated user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: delete_user
      parameters:
      - name: username
        in: path
        description: The name that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /fake_classname_test:
    patch:
      tags:
      - fake_classname_tags 123#$%^
      summary: To test class name in snake case
      operationId: test_classname
      requestBody:
        description: client model
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
      security:
      - api_key_query: []
      x-openapi-router-controller: swagger_server.controllers.fake_classname_tags_123#__%^controller
  /fake:
    get:
      tags:
      - fake
      summary: To test enum parameters
      description: To test enum parameters
      operationId: test_enum_parameters
      parameters:
      - name: enum_header_string_array
        in: header
        description: Header parameter enum test (string array)
        required: false
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            default: $
            enum:
            - '>'
            - $
      - name: enum_header_string
        in: header
        description: Header parameter enum test (string)
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: -efg
          enum:
          - _abc
          - -efg
          - (xyz)
      - name: enum_query_string_array
        in: query
        description: Query parameter enum test (string array)
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            default: $
            enum:
            - '>'
            - $
      - name: enum_query_string
        in: query
        description: Query parameter enum test (string)
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: -efg
          enum:
          - _abc
          - -efg
          - (xyz)
      - name: enum_query_integer
        in: query
        description: Query parameter enum test (double)
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          enum:
          - 1
          - -2
      responses:
        "400":
          description: Invalid request
          content: {}
        "404":
          description: Not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.fake_controller
    post:
      tags:
      - fake
      summary: |
        Fake endpoint for testing various parameters
        假端點
        偽のエンドポイント
        가짜 엔드 포인트
      description: |
        Fake endpoint for testing various parameters
        假端點
        偽のエンドポイント
        가짜 엔드 포인트
      operationId: test_endpoint_parameters
      requestBody:
        content:
          application/xml; charset=utf-8:
            schema:
              $ref: '#/components/schemas/fake_body'
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/fake_body_1'
        required: true
      responses:
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
      security:
      - http_basic_test: []
      x-openapi-router-controller: swagger_server.controllers.fake_controller
    patch:
      tags:
      - fake
      summary: To test "client" model
      description: To test "client" model
      operationId: test_client_model
      requestBody:
        description: client model
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/enum/form:
    post:
      tags:
      - fake
      summary: To test enum parameters
      description: To test enum parameters
      operationId: test_enum_request_body
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/enum_form_body'
      responses:
        "400":
          description: Invalid request
          content: {}
        "404":
          description: Not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/outer/number:
    post:
      tags:
      - fake
      description: Test serialization of outer number types
      operationId: fake_outer_number_serialize
      requestBody:
        description: Input number as post body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OuterNumber'
        required: false
      responses:
        "200":
          description: Output number
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OuterNumber'
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/outer/string:
    post:
      tags:
      - fake
      description: Test serialization of outer string types
      operationId: fake_outer_string_serialize
      requestBody:
        description: Input string as post body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OuterString'
        required: false
      responses:
        "200":
          description: Output string
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OuterString'
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/outer/boolean:
    post:
      tags:
      - fake
      description: Test serialization of outer boolean types
      operationId: fake_outer_boolean_serialize
      requestBody:
        description: Input boolean as post body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OuterBoolean'
        required: false
      responses:
        "200":
          description: Output boolean
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OuterBoolean'
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/outer/composite:
    post:
      tags:
      - fake
      description: Test serialization of object with outer number type
      operationId: fake_outer_composite_serialize
      requestBody:
        description: Input composite as post body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OuterComposite'
        required: false
      responses:
        "200":
          description: Output composite
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OuterComposite'
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/jsonFormData:
    post:
      tags:
      - fake
      summary: test json serialization of form data
      operationId: test_json_form_data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/fake_jsonFormData_body'
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /fake/inline-additionalProperties:
    post:
      tags:
      - fake
      summary: test inline additionalProperties
      operationId: test_inline_additional_properties
      requestBody:
        description: request body
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
      x-openapi-router-controller: swagger_server.controllers.fake_controller
  /another-fake/dummy:
    patch:
      tags:
      - $another-fake?
      summary: To test special tags
      description: To test special tags
      operationId: test_special_tags
      requestBody:
        description: client model
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
      x-openapi-router-controller: swagger_server.controllers.__another_fake?controller
  /animal:
    put:
      tags:
      - animal
      summary: Update an existing animal
      operationId: update_animal
      requestBody:
        description: Animal object that needs to be added.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animal'
          application/xml:
            schema:
              $ref: '#/components/schemas/Animal'
        required: true
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Animal not found
          content: {}
        "405":
          description: Validation exception
          content: {}
      x-openapi-router-controller: swagger_server.controllers.animal_controller
    post:
      tags:
      - animal
      summary: Add a new animal to the store
      operationId: add_animal
      requestBody:
        description: Animal object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animal'
          application/xml:
            schema:
              $ref: '#/components/schemas/Animal'
        required: true
      responses:
        "405":
          description: Invalid input
          content: {}
      x-openapi-router-controller: swagger_server.controllers.animal_controller
  /animal/{animalId}:
    get:
      tags:
      - animal
      summary: Find animal by ID
      description: Returns a single animal
      operationId: get_animal_by_id
      parameters:
      - name: animalId
        in: path
        description: ID of pet to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Animal'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.animal_controller
    post:
      tags:
      - animal
      summary: Updates a animal
      operationId: update_animal_with_form
      parameters:
      - name: animalId
        in: path
        description: ID of animal that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/animal_animalId_body'
      responses:
        "405":
          description: Invalid input
          content: {}
      x-openapi-router-controller: swagger_server.controllers.animal_controller
    delete:
      tags:
      - animal
      summary: Deletes a animal
      operationId: delete_animal
      parameters:
      - name: api_key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: animalId
        in: path
        description: Animal id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid animal value
          content: {}
      x-openapi-router-controller: swagger_server.controllers.animal_controller
  /dog:
    put:
      tags:
      - dog
      summary: Update an existing dog
      operationId: update_dog
      requestBody:
        description: Dog object that needs to be added.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
          application/xml:
            schema:
              $ref: '#/components/schemas/Dog'
        required: true
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Animal not found
          content: {}
        "405":
          description: Validation exception
          content: {}
      x-openapi-router-controller: swagger_server.controllers.dog_controller
    post:
      tags:
      - dog
      summary: Add a new dog to the store
      operationId: add_dog
      requestBody:
        description: Dog object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
          application/xml:
            schema:
              $ref: '#/components/schemas/Dog'
        required: true
      responses:
        "405":
          description: Invalid input
          content: {}
      x-openapi-router-controller: swagger_server.controllers.dog_controller
  /dog/{dogId}:
    get:
      tags:
      - dog
      summary: Find dog by ID
      description: Returns a single dog
      operationId: get_dog_by_id
      parameters:
      - name: dogId
        in: path
        description: ID of dog to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Dog'
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.dog_controller
    post:
      tags:
      - dog
      summary: Updates a dog
      operationId: update_dog_with_form
      parameters:
      - name: dogId
        in: path
        description: ID of dog that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/dog_dogId_body'
      responses:
        "405":
          description: Invalid input
          content: {}
      x-openapi-router-controller: swagger_server.controllers.dog_controller
    delete:
      tags:
      - dog
      summary: Deletes a dog
      operationId: delete_dog
      parameters:
      - name: api_key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: dogId
        in: path
        description: Dog id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid dog value
          content: {}
      x-openapi-router-controller: swagger_server.controllers.dog_controller
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        id: 0
        category: test-category-name
      xml:
        name: Category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-is-unique: true
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
      example:
        id: 0
        username: hugomario
        firstName: hugo
        lastName: mercado
        email: hugo.mercado.aws@gmail.com
        password: '*****'
        phone: 000-00000000
        userStatus: 1
      xml:
        name: User
    OuterNumber:
      type: number
    ArrayOfNumberOnly:
      type: object
      properties:
        ArrayNumber:
          type: array
          items:
            type: number
      example:
        id: 0
        ArrayNumber:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
    Capitalization:
      type: object
      properties:
        smallCamel:
          type: string
        CapitalCamel:
          type: string
        small_Snake:
          type: string
        Capital_Snake:
          type: string
        SCA_ETH_Flow_Points:
          type: string
        ATT_NAME:
          type: string
          description: |
            Name of the pet
      example:
        smallCamel: testProperty
        CapitalCamel: TestProperty
        small_Snake: test_property
        Capital_Snake: Test_Property
    MixedPropertiesAndAdditionalPropertiesClass:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        dateTime:
          type: string
          format: date-time
        map:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Animal'
      example:
        uuid: bbe4001e-f700-11e8-8eb2-f2801f1b9fd1
        dateTime: 2018-11-05 09:25
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      example:
        code: 0
        type: type
        message: message
    Name:
      required:
      - name
      type: object
      properties:
        name:
          type: integer
          format: int32
        snake_case:
          type: integer
          format: int32
          readOnly: true
        property:
          type: string
        "123Number":
          type: integer
          readOnly: true
      description: Model for testing model name same as property name
      xml:
        name: Name
    EnumClass:
      type: string
      default: -efg
      enum:
      - _abc
      - -efg
      - (xyz)
    List:
      type: object
      properties:
        "123-list":
          type: string
    NumberOnly:
      type: object
      properties:
        JustNumber:
          type: number
    "200_response":
      type: object
      properties:
        name:
          type: integer
          format: int32
        class:
          type: string
      description: Model for testing model name starting with number
      xml:
        name: Name
    Client:
      type: object
      properties:
        client:
          type: string
      example:
        client: client
    Dog:
      allOf:
      - $ref: '#/components/schemas/Animal'
      - type: object
        properties:
          breed:
            type: string
    Enum_Test:
      type: object
      properties:
        enum_string:
          type: string
          enum:
          - UPPER
          - lower
          - ""
        enum_integer:
          type: integer
          format: int32
          enum:
          - 1
          - -1
        enum_number:
          type: number
          format: double
          enum:
          - 1.1
          - -1.2
        outerEnum:
          $ref: '#/components/schemas/OuterEnum'
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
          default: false
      example:
        petId: 6
        quantity: 1
        id: 0
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: false
        status: placed
      xml:
        name: Order
    AdditionalPropertiesClass:
      type: object
      properties:
        map_property:
          type: object
          additionalProperties:
            type: string
        map_of_map_property:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: string
    $special[model.name]:
      type: object
      properties:
        $special[property.name]:
          type: integer
          format: int64
      xml:
        name: "$special[model.name]"
    Return:
      type: object
      properties:
        return:
          type: integer
          format: int32
      description: Model for testing reserved words
      xml:
        name: Return
    ReadOnlyFirst:
      type: object
      properties:
        bar:
          type: string
          readOnly: true
        baz:
          type: string
    ArrayOfArrayOfNumberOnly:
      type: object
      properties:
        ArrayArrayNumber:
          type: array
          items:
            type: array
            items:
              type: number
    OuterEnum:
      type: string
      enum:
      - placed
      - approved
      - delivered
    ArrayTest:
      type: object
      properties:
        array_of_string:
          type: array
          items:
            type: string
        array_array_of_integer:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int64
        array_array_of_model:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/ReadOnlyFirst'
    OuterComposite:
      type: object
      properties:
        my_number:
          $ref: '#/components/schemas/OuterNumber'
        my_string:
          $ref: '#/components/schemas/OuterString'
        my_boolean:
          $ref: '#/components/schemas/OuterBoolean'
      example:
        my_string: my_string
        my_number: 0.8008281904610115
        my_boolean: true
    format_test:
      required:
      - byte
      - date
      - number
      - password
      type: object
      properties:
        integer:
          maximum: 100.0
          minimum: 10.0
          type: integer
        int32:
          maximum: 200.0
          minimum: 20.0
          type: integer
          format: int32
        int64:
          type: integer
          format: int64
        number:
          maximum: 543.2
          minimum: 32.1
          type: number
        float:
          maximum: 987.6
          minimum: 54.3
          type: number
          format: float
        double:
          maximum: 123.4
          minimum: 67.8
          type: number
          format: double
        string:
          pattern: "/[a-z]/i"
          type: string
        byte:
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
          format: byte
        binary:
          type: string
          format: binary
        date:
          type: string
          format: date
        dateTime:
          type: string
          format: date-time
        uuid:
          type: string
          format: uuid
        password:
          maxLength: 64
          minLength: 10
          type: string
          format: password
    EnumArrays:
      type: object
      properties:
        just_symbol:
          type: string
          enum:
          - '>='
          - $
        array_enum:
          type: array
          items:
            type: string
            enum:
            - fish
            - crab
    OuterString:
      type: string
    ClassModel:
      type: object
      properties:
        _class:
          type: string
      description: Model for testing model with "_class" property
    OuterBoolean:
      type: boolean
    Animal:
      required:
      - className
      type: object
      properties:
        className:
          type: string
        color:
          type: string
          default: red
      example:
        color: red
        className: className
      discriminator:
        propertyName: className
    Cat:
      allOf:
      - $ref: '#/components/schemas/Animal'
      - type: object
        properties:
          declawed:
            type: boolean
    MapTest:
      type: object
      properties:
        map_map_of_string:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: string
        map_of_enum_string:
          type: object
          additionalProperties:
            type: string
            enum:
            - UPPER
            - lower
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    AnimalFarm:
      type: array
      items:
        $ref: '#/components/schemas/Animal'
    Pet:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-is-unique: true
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
      example:
        photoUrls:
        - photoUrls
        - photoUrls
        name: doggie
        id: 0
        category:
          name: name
          id: 6
        tags:
        - name: name
          id: 1
        - name: name
          id: 1
        status: available
      xml:
        name: Pet
    NullableEnumModel:
      type: object
      properties:
        enumProp:
          type: string
          nullable: true
          enum:
          - a
          - b
          - null
    SinglePetResponse:
      type: object
      properties:
        pet:
          discriminator:
            propertyName: pet_type
          oneOf:
          - $ref: '#/components/schemas/Dog'
          - $ref: '#/components/schemas/Cat'
      example:
        pet: ""
    AllPetsResponse:
      type: array
      items:
        discriminator:
          propertyName: pet_type
        oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
    SubCategory:
      type: object
      properties:
        category:
          allOf:
          - $ref: '#/components/schemas/Category'
          - type: object
            properties:
              foo:
                type: boolean
              bar:
                type: integer
              beer:
                type: string
              drunk:
                $ref: '#/components/schemas/User'
        category2:
          $ref: '#/components/schemas/Category'
        pets:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Pet'
    hasOnlyReadOnly:
      type: object
      properties:
        bar:
          type: string
          readOnly: true
        foo:
          type: string
          readOnly: true
    pet_petId_body:
      properties:
        name:
          type: string
          description: Updated name of the pet
        status:
          type: string
          description: Updated status of the pet
    petId_uploadImage_body:
      properties:
        additionalMetadata:
          type: string
          description: Additional data to pass to server
        file:
          type: string
          description: file to upload
          format: binary
    fake_body:
      required:
      - byte
      - double
      - number
      - pattern_without_delimiter
      properties:
        integer:
          maximum: 100
          minimum: 10
          type: integer
          description: None
        int32:
          maximum: 200
          minimum: 20
          type: integer
          description: None
          format: int32
        int64:
          type: integer
          description: None
          format: int64
        number:
          maximum: 543.2
          minimum: 32.1
          type: number
          description: None
        float:
          maximum: 987.6
          type: number
          description: None
          format: float
        double:
          maximum: 123.4
          minimum: 67.8
          type: number
          description: None
          format: double
        string:
          pattern: "/[a-z]/i"
          type: string
          description: None
        pattern_without_delimiter:
          pattern: "^[A-Z].*"
          type: string
          description: None
        byte:
          type: string
          description: None
          format: byte
        binary:
          type: string
          description: None
          format: binary
        date:
          type: string
          description: None
          format: date
        dateTime:
          type: string
          description: None
          format: date-time
        password:
          maxLength: 64
          minLength: 10
          type: string
          description: None
          format: password
        callback:
          type: string
          description: None
    fake_body_1:
      required:
      - byte
      - double
      - number
      - pattern_without_delimiter
      properties:
        integer:
          maximum: 100
          minimum: 10
          type: integer
          description: None
        int32:
          maximum: 200
          minimum: 20
          type: integer
          description: None
          format: int32
        int64:
          type: integer
          description: None
          format: int64
        number:
          maximum: 543.2
          minimum: 32.1
          type: number
          description: None
        float:
          maximum: 987.6
          type: number
          description: None
          format: float
        double:
          maximum: 123.4
          minimum: 67.8
          type: number
          description: None
          format: double
        string:
          pattern: "/[a-z]/i"
          type: string
          description: None
        pattern_without_delimiter:
          pattern: "^[A-Z].*"
          type: string
          description: None
        byte:
          type: string
          description: None
          format: byte
        binary:
          type: string
          description: None
          format: binary
        date:
          type: string
          description: None
          format: date
        dateTime:
          type: string
          description: None
          format: date-time
        password:
          maxLength: 64
          minLength: 10
          type: string
          description: None
          format: password
        callback:
          type: string
          description: None
    enum_form_body:
      properties:
        enum_form_string_array:
          type: array
          description: Form parameter enum test (string array)
          items:
            type: string
            default: $
            enum:
            - '>'
            - $
        enum_form_string:
          type: string
          description: Form parameter enum test (string)
          default: -efg
          enum:
          - _abc
          - -efg
          - (xyz)
        enum_query_double:
          type: number
          description: Query parameter enum test (double)
          format: double
          enum:
          - 1.1
          - -1.2
    fake_jsonFormData_body:
      required:
      - param
      - param2
      properties:
        param:
          type: string
          description: field1
        param2:
          type: string
          description: field2
    animal_animalId_body:
      properties:
        name:
          type: string
          description: Updated name of the animal
        status:
          type: string
          description: Updated status of the animal
    dog_dogId_body:
      properties:
        name:
          type: string
          description: Updated name of the dog
        status:
          type: string
          description: Updated status of the dog
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_petstore_auth
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_petstore_auth
    http_basic_test:
      type: http
      scheme: basic
      x-basicInfoFunc: swagger_server.controllers.authorization_controller.check_http_basic_test
    api_key:
      type: apiKey
      name: api_key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key
    api_key_query:
      type: apiKey
      name: api_key_query
      in: query
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key_query

